export const GET_ROOMS_BY_OWNER = 'GET_ROOMS_BY_OWNER';
export const GET_ROOMS_DETAILS = 'GET_ROOMS_DETAILS';
export const GET_ROOM = 'GET_ROOM';
export const GET_REQUEST_STATUS = 'GET_REQUEST_STATUS';

export const GET_ROUND_DETAILS = 'GET_ROUND_DETAILS';
export const GET_DEALER_ROOM = 'GET_DEALER_ROOM';
export const GET_PLAY_ROOM = 'GET_PLAY_ROOM';

export const SOCKET_ROUND_START = 'SOCKET_ROUND_START';
export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const USER_PROFILE = 'USER_PROFILE';
